#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("XamarinGame.Droid.Resource", IsApplication=true)]

namespace XamarinGame.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int button_background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int hangman_blank = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int hangman_word = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int title_bar = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int word_question = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050004
			public const int ImageWordSlot01 = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int ImageWordSlot02 = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int ImageWordSlot03 = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int ImageWordSlot04 = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int ImageWordSlot05 = 2131034120;
			
			// aapt resource value: 0x7f050001
			public const int TitleLayout = 2131034113;
			
			// aapt resource value: 0x7f05000a
			public const int btn01 = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int btn02 = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int btn03 = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int btn04 = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int btn05 = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int btn06 = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int btn07 = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int btn08 = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int btn09 = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int btn10 = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int btn11 = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int btn12 = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int btn13 = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int btn14 = 2131034135;
			
			// aapt resource value: 0x7f050018
			public const int btn15 = 2131034136;
			
			// aapt resource value: 0x7f05001b
			public const int btnProfile = 2131034139;
			
			// aapt resource value: 0x7f050020
			public const int btnSave = 2131034144;
			
			// aapt resource value: 0x7f05001a
			public const int btnScores = 2131034138;
			
			// aapt resource value: 0x7f050019
			public const int btnStartGame = 2131034137;
			
			// aapt resource value: 0x7f050022
			public const int button1 = 2131034146;
			
			// aapt resource value: 0x7f050023
			public const int button2 = 2131034147;
			
			// aapt resource value: 0x7f05001c
			public const int button3 = 2131034140;
			
			// aapt resource value: 0x7f05001f
			public const int editTextProfile = 2131034143;
			
			// aapt resource value: 0x7f050009
			public const int imageView = 2131034121;
			
			// aapt resource value: 0x7f050000
			public const int imageView2 = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int imageView3 = 2131034115;
			
			// aapt resource value: 0x7f050021
			public const int listProfile = 2131034145;
			
			// aapt resource value: 0x7f050024
			public const int relativeLayout1 = 2131034148;
			
			// aapt resource value: 0x7f05001e
			public const int textView1 = 2131034142;
			
			// aapt resource value: 0x7f05001d
			public const int textViewMessage = 2131034141;
			
			// aapt resource value: 0x7f050002
			public const int textViewTitle = 2131034114;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int game_layout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int main_layout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int profile_layout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int scores_layout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int screen_layout = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
