#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("HangmanApp.Droid.Resource", IsApplication=true)]

namespace HangmanApp.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Splat.Resource.String.library_name = global::HangmanApp.Droid.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int button_background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int hangman00 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int hangman01 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int hangman02 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int hangman03 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int hangman04 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int hangman05 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int hangman06 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int hangman_blank = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int hangman_word = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int letter_a = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int letter_b = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int letter_c = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int letter_d = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int letter_e = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int letter_f = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int letter_g = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int letter_h = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int letter_i = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int letter_j = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int letter_k = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int letter_l = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int letter_m = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int letter_n = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int letter_o = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int letter_p = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int letter_q = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int letter_r = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int letter_s = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int letter_t = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int letter_u = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int letter_v = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int letter_w = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int letter_x = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int letter_y = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int letter_z = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int profile_border = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int question_mark = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int title_bar = 2130837542;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050021
			public const int CreateProfileLayout = 2131034145;
			
			// aapt resource value: 0x7f050008
			public const int ImageSlot01 = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int ImageSlot02 = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int ImageSlot03 = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int ImageSlot04 = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int ImageSlot05 = 2131034124;
			
			// aapt resource value: 0x7f050025
			public const int ListProfile = 2131034149;
			
			// aapt resource value: 0x7f050000
			public const int TitleLayout = 2131034112;
			
			// aapt resource value: 0x7f05000d
			public const int btn01 = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int btn02 = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int btn03 = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int btn04 = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int btn05 = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int btn06 = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int btn07 = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int btn08 = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int btn09 = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int btn10 = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int btn11 = 2131034135;
			
			// aapt resource value: 0x7f050018
			public const int btn12 = 2131034136;
			
			// aapt resource value: 0x7f050019
			public const int btn13 = 2131034137;
			
			// aapt resource value: 0x7f05001a
			public const int btn14 = 2131034138;
			
			// aapt resource value: 0x7f05001b
			public const int btn15 = 2131034139;
			
			// aapt resource value: 0x7f050024
			public const int btnCancel = 2131034148;
			
			// aapt resource value: 0x7f050026
			public const int btnCreate = 2131034150;
			
			// aapt resource value: 0x7f05001f
			public const int btnCredits = 2131034143;
			
			// aapt resource value: 0x7f05001e
			public const int btnProfile = 2131034142;
			
			// aapt resource value: 0x7f050023
			public const int btnSave = 2131034147;
			
			// aapt resource value: 0x7f05001d
			public const int btnScores = 2131034141;
			
			// aapt resource value: 0x7f05001c
			public const int btnStartGame = 2131034140;
			
			// aapt resource value: 0x7f050007
			public const int btnStartNew = 2131034119;
			
			// aapt resource value: 0x7f050022
			public const int editTextProfile = 2131034146;
			
			// aapt resource value: 0x7f050006
			public const int imageViewHangman = 2131034118;
			
			// aapt resource value: 0x7f050027
			public const int listViewScores = 2131034151;
			
			// aapt resource value: 0x7f050002
			public const int textViewHighest = 2131034114;
			
			// aapt resource value: 0x7f050020
			public const int textViewMessage = 2131034144;
			
			// aapt resource value: 0x7f050005
			public const int textViewProfile = 2131034117;
			
			// aapt resource value: 0x7f050003
			public const int textViewScore = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int textViewTimer = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int textViewTitle = 2131034113;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Layout_Game = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Layout_MainScreen = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Layout_Profile_v2 = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Layout_Scores = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
