#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("GameAppV1.Resource", IsApplication=true)]

namespace GameAppV1
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int hangman_base = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int hangman_blank = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int hangman_tile_01_A = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int hangman_tile_01_B = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int hangman_tile_02_A = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int hangman_tile_02_B = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int hangman_tile_03_A = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int hangman_tile_03_B = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int hangman_tile_04_A = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int hangman_tile_04_B = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int hangman_tile_05_A = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int hangman_tile_05_B = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int hangman_tile_06_A = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int hangman_tile_06_B = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int hangman_tile_07_A = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int hangman_title = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int hangman_word = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int Icon = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int word_A = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int word_B = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int word_C = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int word_D = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int word_E = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int word_end = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int word_F = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int word_G = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int word_H = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int word_I = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int word_J = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int word_K = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int word_L = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int word_M = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int word_N = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int word_O = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int word_P = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int word_Q = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int word_question = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int word_R = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int word_S = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int word_start = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int word_T = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int word_U = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int word_V = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int word_W = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int word_X = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int word_Y = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int word_Z = 2130837550;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int ImageTile01 = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int ImageTile02 = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int ImageTile03 = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int ImageTile04 = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int ImageTile05 = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int ImageTile06 = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int ImageWordSlot01 = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int btnPressMe = 2131034119;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
